version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lojadb
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data 