INTENT_LABELS = [
    "listar_produtos",
    "listar_vendas",
    "quantidade_produtos_vendidos",
    "valor_total_vendido",
    "outro"
]

EXEMPLOS_TREINO = [

    ("Quais são os produtos que vocês têm?", "listar_produtos"),
    ("Tem produto cadastrado aí?", "listar_produtos"),
    ("Me mostra aí o que tem na loja", "listar_produtos"),
    ("Quero saber o que tá disponível pra vender", "listar_produtos"),
    ("Manda a lista dos produtos pra mim", "listar_produtos"),
    ("Produtos disponíveis no sistema, por favor", "listar_produtos"),
    ("Tem como ver os itens em estoque?", "listar_produtos"),
    ("Lista tudo que tá no catálogo", "listar_produtos"),
    ("Me mostra os nomes dos produtos", "listar_produtos"),
    ("Cadê a lista de produtos?", "listar_produtos"),
    ("Quero saber o que posso comprar", "listar_produtos"),
    ("Tem algo pra mostrar aí de produto?", "listar_produtos"),
    ("Lista os itens aí", "listar_produtos"),
    ("Tem produto novo?", "listar_produtos"),
    ("Quero os produtos ordenados por nome", "listar_produtos"),


    # listar_vendas
    ("Me mostra o que foi vendido até agora", "listar_vendas"),
    ("Tem venda registrada aí?", "listar_vendas"),
    ("Quero ver as últimas vendas feitas", "listar_vendas"),
    ("Me dá um histórico de vendas", "listar_vendas"),
    ("Quais foram as vendas mais recentes?", "listar_vendas"),
    ("Tem como puxar a lista de vendas?", "listar_vendas"),
    ("O que já foi vendido esse mês?", "listar_vendas"),
    ("Tem venda de hoje?", "listar_vendas"),
    ("Vendas por valor, mostra aí", "listar_vendas"),
    ("As vendas estão indo bem?", "listar_vendas"),
    ("Quero ver quais produtos foram vendidos", "listar_vendas"),
    ("Exibe as vendas feitas por data", "listar_vendas"),
    ("Como estão as vendas desse período?", "listar_vendas"),
    ("Mostre o log de vendas", "listar_vendas"),
    ("Me mostra as transações feitas", "listar_vendas"),


    # quantidade_produtos_vendidos
    ("Quantos itens já saíram?", "quantidade_produtos_vendidos"),
    ("Me passa a quantidade de produtos vendidos", "quantidade_produtos_vendidos"),
    ("Unidades vendidas no dia?", "quantidade_produtos_vendidos"),
    ("Total vendido em número de produtos", "quantidade_produtos_vendidos"),
    ("Quantos foram vendidos no total?", "quantidade_produtos_vendidos"),
    ("Já vendeu muito hoje?", "quantidade_produtos_vendidos"),
    ("Quantas saídas foram feitas?", "quantidade_produtos_vendidos"),
    ("Tem o número de unidades vendidas aí?", "quantidade_produtos_vendidos"),
    ("Quantos itens o sistema marcou como vendidos?", "quantidade_produtos_vendidos"),
    ("Quantos produtos saíram no mês?", "quantidade_produtos_vendidos"),
    ("Tem o total vendido em unidades?", "quantidade_produtos_vendidos"),
    ("Quantas vendas até agora?", "quantidade_produtos_vendidos"),
    ("Me fala o número total de vendas", "quantidade_produtos_vendidos"),
    ("Quantas unidades a gente vendeu hoje?", "quantidade_produtos_vendidos"),
    ("Saiu quantos itens do estoque?", "quantidade_produtos_vendidos"),

    # valor_total_vendido
    ("Quanto arrecadamos hoje?", "valor_total_vendido"),
    ("Qual o faturamento total agora?", "valor_total_vendido"),
    ("Me diz quanto entrou de dinheiro", "valor_total_vendido"),
    ("Dinheiro total das vendas?", "valor_total_vendido"),
    ("Receita total do mês", "valor_total_vendido"),
    ("Quanto deu no caixa pelas vendas?", "valor_total_vendido"),
    ("Qual foi o total financeiro vendido?", "valor_total_vendido"),
    ("Receita obtida pelas vendas", "valor_total_vendido"),
    ("Quanto a gente faturou hoje?", "valor_total_vendido"),
    ("Valor vendido até agora", "valor_total_vendido"),
    ("Faturamento de hoje", "valor_total_vendido"),
    ("Tem valor total aí?", "valor_total_vendido"),
    ("Entrou quanto com as vendas?", "valor_total_vendido"),
    ("Qual a soma em R$ das vendas?", "valor_total_vendido"),
    ("Me passa o valor total do que foi vendido", "valor_total_vendido"),

    ("qual é a capital da frança?", "outro"),
    ("me conte uma piada", "outro"),
    ("como está o tempo hoje?", "outro"),
    ("quem é você?", "outro"),
    ("gosto de café", "outro"),
    ("isso não tem nada a ver com vendas", "outro"),
    ("qual é seu nome?", "outro"),
    ("me fale sobre inteligência artificial", "outro"),
    ("ajuda", "outro"),
    ("quero sair", "outro"),
    ("dsajkdasjkjkdajk djakjdsajkjk dajdjksada", "outro"),
    ("tabela fornecedores", "outro"),
    ("videogames", "outro"),
    ("filmes espaciais", "outro"),
    ("verdão do sul azul", "outro"),
    ("voce mostra a escola para mim", "outro"),
    ("me exiba o nada", "outro"),
    ("teste", "outro"),
    ("o rato roe", "outro")

]
